development:
  adapter: postgresql
  encoding: unicode
  database: rails_base
  pool: 5
  username: ilnar
  password: password
  template: template0
  host: localhost
  port: 5432
  
test: &test
  adapter: postgresql
  encoding: unicode
  database: test_rails_base
  username: ilnar
  password: password
  pool: 5
  template: template0
  host: localhost
  port: 5432

production: &deploy
  adapter: postgresql
  encoding: unicode
  min_messages: warning
  timeout: 5000
  pool: <%= [ENV.fetch("MAX_THREADS", 5), ENV.fetch("DB_POOL", 5)].max %>
staging: *deploy
